language: java
sudo: true
before_install:
  - wget -O lein "https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein"
  - chmod +x lein
before_script:
  - ./lein version
script:
  - cd lein-ancient && ../lein isolated deps && ../lein isolated midje
  - cd ../ancient-clj && ../lein deps && ../lein test
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
